# Generated by Django 5.0.3 on 2024-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="slider",
            name="contact_link",
            field=models.URLField(default="https://www.youtube.com/"),
        ),
    ]
