# Generated by Django 5.0.3 on 2024-03-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0002_slider_contact_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("photo", models.ImageField(upload_to="team/%Y/%m")),
                ("facebook_link", models.URLField(default="https://www.facebook.com/")),
                ("linkedin_link", models.URLField(default="https://www.linkedin.com/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
