# Generated by Django 5.0.3 on 2024-03-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpages", "0003_ourteam"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ourteam",
            options={"verbose_name": "Our Team", "verbose_name_plural": "Our Team"},
        ),
    ]
