# Generated by Django 5.0.3 on 2024-03-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Youtuber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("channel_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("crew", models.CharField(max_length=255)),
                ("camera_type", models.CharField(max_length=255)),
                ("sub_count", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("channel_link", models.URLField(default="https://www.youtube.com")),
                ("age", models.IntegerField()),
                ("hieght", models.IntegerField()),
                ("price", models.IntegerField()),
                ("photo", models.ImageField(upload_to="youtubers/%Y/%m/%d")),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
