# Generated by Django 5.0.3 on 2024-03-23 06:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("youtubers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtuber",
            name="camera_type",
            field=models.CharField(
                choices=[
                    ("dslr", "DSLR"),
                    ("mirrorless", "Mirrorless"),
                    ("compact", "Compact"),
                    ("action", "Action"),
                    ("drone", "Drone"),
                    ("other", "Other"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="youtuber",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Tech"),
                    ("gaming", "Gaming"),
                    ("vlogs", "Vlogs"),
                    ("cooking", "Cooking"),
                    ("music", "Music"),
                    ("fitness", "Fitness"),
                    ("travel", "Travel"),
                    ("other", "Other"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="youtuber",
            name="crew",
            field=models.CharField(
                choices=[
                    ("solo", "solo"),
                    ("small", "small (3-5 people)"),
                    ("large", "large (5+ people)"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="youtuber",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
