# Generated by Django 5.0.3 on 2024-03-24 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "youtubers",
            "0002_alter_youtuber_camera_type_alter_youtuber_category_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtuber", old_name="hieght", new_name="height",
        ),
    ]
